name: AWS EC2 Self Hosted Runner
description: Create a self hosted runner on AWS EC2
author: Kepler Authors

# Define your inputs here.
inputs:
  who-to-greet:
    description: Who to greet
    required: false
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
