name: AWS EC2 Self Hosted Runner
description: Create a self hosted runner on AWS EC2
author: Kepler Authors

# Define your outputs here.
outputs:
  instane_id:
    description: The AWS EC2 instance id
  runner_name:
    description: The name of the self hosted runner
  bucket_name:
    description: The name of the S3 bucket (if created)

runs:
  using: docker
  image: Dockerfile
  env:
    # ACTION is one of create, unregister, terminate
    ACTION: "create|unregister|terminate" 
    # aws region to use, this could be an input parameter or a secret
    AWS_REGION: ${{ secrets.AWS_REGION }}
    # github token to use, this should be a secret
    GITHUB_TOKEN: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
    # aws access key id and secret access key, these should be secrets
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # AWS security group id, this could be an input parameter or a secret
    SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
    # github repository to use, this could be an input parameter or a secret
    GITHUB_REPO: ${{ github.repository }}
    AMI_ID: ami-0e4d0bb9670ea8db0
    INSTANCE_TYPE: t2.micro
    CREATE_S3_BUCKET: false
    SPOT_INSTANCE_ONLY: true
