name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
  GITHUB_REPO: ${{ github.repository }}
  AMI_ID: ${{ github.event.inputs.ami_id }}
  INSTANCE_TYPE: ${{ github.event.inputs.instance_type }}

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/hello-world-docer-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}


  test-action-create-instance:
    name: GitHub Actions Test create instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          action: create

    test:
      needs: test-action-create-instance
      runs-on: self-hosted
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          export INSTANCE_ID=${{ needs.test-action-create-instance.outputs.instance_id }}
          echo "Running tests on self-hosted runner with instance $INSTANCE_ID"
          uname -a # or any other command

    test-action-destroy-instance:
      name: GitHub Actions Test destroy instance
      needs: [test-action-create-instance, test]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Test Local Action
          id: test-action
          uses: ./
          with:
            RUNNER_NAME: ${{ needs.test-action-create-instance.outputs.runner_name }}
            action: unregister

        - name: Test Local Action
          id: test-action
          uses: ./
          with:
            INSTANCE_ID: ${{ needs.test-action-create-instance.outputs.instance_id }}
            action: terminate
            