# shellcheck disable=SC1000-SC9999
name: Continuous Integration Entry

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unitpreOS:
    strategy:
      matrix:
      # us-east-2
      # Ubuntu 20.04 AMI is ami-0e4d0bb9670ea8db0
      # ubuntu 22.04 AMI is ami-05fb0b8c1424f266b 
      # RHEL 9       AMI is ami-078cbc4c2d057c244
        AMI_ID: [ami-0e4d0bb9670ea8db0,ami-05fb0b8c1424f266b,ami-078cbc4c2d057c244]
    uses: ./.github/workflows/ci_unit.yml
    secrets:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GH_SELF_HOSTED_RUNNER_TOKEN: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
        AMI_ID:  ${{matrix.AMI_ID}}
   