name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read
  
  jobs:
    name: build image and push
    runs-on: ubuntu-latest
    build_and_push_image:
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}
      
      - name: Build and push the container
        uses: docker/build-push-action@v5
        with:
            context: .
            platforms: linux/amd64
            push: true
            tags: quay.io/sustainable_computing_io/aws_ec2_self_hosted_runner:latest
            labels: latest
            file: Dockerfile